# Fly.io configuration for Sysora Hotel Management Platform
app = "sysora-hotel-platform"
primary_region = "fra"  # Frankfurt region for better latency to Middle East/North Africa
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  APP_NAME = "Sysora Hotel Management Platform"
  APP_VERSION = "1.0.0"
  DEFAULT_TIMEZONE = "Africa/Algiers"
  DEFAULT_LANGUAGE = "ar"
  SUPPORTED_LANGUAGES = "ar,en,fr"
  MONGODB_URI = "mongodb+srv://sysoradb:y7aSBmomOzB52wO3@sysoradb.iera7dr.mongodb.net/sysora-hotel?retryWrites=true&w=majority"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[machine]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    timeout = "4s"
    tls_skip_verify = false

# [deploy]
  # Build happens in Dockerfile, no release command needed

[[mounts]]
  source = "sysora_uploads"
  destination = "/app/uploads"

[processes]
  app = "npm start"

[experimental]
  auto_rollback = true
